-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Июл 13 2024 г., 02:31
-- Версия сервера: 10.4.27-MariaDB
-- Версия PHP: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `palumni`
--

-- --------------------------------------------------------

--
-- Структура таблицы `languages`
--

CREATE TABLE `languages` (
  `id` int(11) NOT NULL,
  `en` text NOT NULL,
  `ua` text NOT NULL,
  `sk` text NOT NULL,
  `pl` text NOT NULL,
  `ru` text NOT NULL,
  `de` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Дамп данных таблицы `languages`
--

INSERT INTO `languages` (`id`, `en`, `ua`, `sk`, `pl`, `ru`, `de`) VALUES
(1, 'About us', 'Про нас', 'O nás', 'O nas', 'О нас', 'Über uns'),
(2, 'Who we are?', 'Хто ми?', 'Kto sme?', 'Kim jesteśmy?', 'Кто мы?', 'Wer sind wir?'),
(3, 'is a team of developers who specialize in creating custom websites that are visually appealing, user-friendly, and optimized for all devices. Our team offers tailored web design, responsive development, e-commerce solutions, and ongoing support to help your business thrive online', 'це команда розробників, які спеціалізуються на створенні індивідуальних веб-сайтів, візуально привабливих, зручних для користувача та оптимізованих для всіх пристроїв. Наша команда пропонує індивідуальний веб-дизайн, адаптивну розробку, e-commerce рішення та постійну підтримку, щоб допомогти вашому бізнесу процвітати в Інтернеті', 'je tím vývojárov, ktorí sa špecializujú na tvorbu prispôsobených webových stránok, ktoré sú vizuálne príťažlivé, užívateľsky prívetivé a optimalizované pre všetky zariadenia. Náš tím ponúka prispôsobený webdizajn, responzívny vývoj, riešenia pre elektronický obchod a neustálu podporu, aby váš biznis mohol online prosperovať.', 'to zespół deweloperów specjalizujących się w tworzeniu niestandardowych stron internetowych, które są atrakcyjne wizualnie, przyjazne dla użytkownika i zoptymalizowane dla wszystkich urządzeń. Nasz zespół oferuje dostosowany projekt stron internetowych, responsywne rozwiązania, e-commerce oraz wsparcie, które pomoże Twojemu biznesowi rozkwitnąć online', 'команда разработчиков, которые специализируются на создании пользовательских веб-сайтов, которые визуально привлекательны, удобны в использовании и оптимизированы для всех устройств. Наша команда предлагает индивидуальный веб-дизайн, адаптивную разработку, решения для электронной коммерции и постоянную поддержку, чтобы помочь вашему бизнесу процветать в Интернете', 'ist ein Team von Entwicklern, das sich auf die Erstellung maßgeschneiderter Websites spezialisiert hat, die optisch ansprechend, benutzerfreundlich und für alle Geräte optimiert sind. Unser Team bietet maßgeschneidertes Webdesign, responsive Entwicklung, E-Commerce-Lösungen und kontinuierlichen Support, um Ihrem Unternehmen online zum Erfolg zu verhelfen'),
(4, 'Contact us', 'Зв\'язатися з нами', 'Kontaktujte nás', 'Skontaktuj się z nami', 'Свяжитесь с нами', 'Kontakt'),
(5, 'Services', 'Послуги', 'Služby', 'Usługi', 'Услуги', 'Dienste'),
(6, 'Portfolio', 'Портфоліо', 'Portfólio', 'Portfolio', 'Портфолио', 'Portfolio'),
(7, 'Turning Ideas into Digital Success', 'Перетворюємо Ідеї На Цифровий Успіх', 'Premieňame Nápady Na Digitálny Uspech', 'Przemienianie pomysłów w cyfrowy sukces', 'Превращаем Идеи В Цифровой Успех', 'Ideen In Digitalen Erfolg Umwandeln'),
(8, 'Also we create turnkey Telegram Bots to enhance customer engagement and streamline communication', 'Також ми створюємо Telegram-ботів під ключ для підвищення залученості клієнтів та оптимізації комунікації', 'Taktiež vytvárame Telegram boty na kľúč, aby sme zlepšili angažovanosť zákazníkov a zefektívnili komunikáciu', 'Tworzymy również gotowe Boty Telegram, które zwiększają zaangażowanie klientów i usprawniają komunikację\r\n', 'Также мы создаем Telegram-ботов под ключ для повышения взаимодействия с клиентами и упрощения коммуникации', 'Wir erstellen auch schlüsselfertige Telegram-Bots, um die Kundenbindung zu verbessern und die Kommunikation zu optimieren'),
(10, 'We offer additional services like Web-Scraping, technical support, and digital marketing, providing tailored solutions to enhance your online presence and streamline your business operations', 'Ми пропонуємо додаткові послуги, такі як Web-Scraping, технічна підтримка та цифровий маркетинг, надаючи індивідуальні рішення для розширення вашої діяльності в Інтернеті та оптимізації ваших бізнес-операцій', 'Ponúkame ďalšie služby, ako je Web-Scraping, technická podpora a digitálny marketing, poskytujúc prispôsobené riešenia na zlepšenie vašej online prítomnosti a zefektívnenie obchodných operácií', 'Oferujemy dodatkowe usługi, takie jak Web-Scraping, wsparcie techniczne i marketing cyfrowy, zapewniając dostosowane rozwiązania, które zwiększają Twoją obecność online i usprawniają działalność biznesową\r\n', 'Мы предлагаем дополнительные услуги, такие как Web-Scraping, техническая поддержка и цифровой маркетинг, предоставляя индивидуальные решения для улучшения вашего присутствия в Интернете и оптимизации бизнес-операций.', 'Wir bieten zusätzliche Dienstleistungen wie Web-Scraping, technischen Support und digitales Marketing an und bieten maßgeschneiderte Lösungen zur Verbesserung Ihrer Online-Präsenz und zur Optimierung Ihrer Geschäftsabläufe.'),
(11, 'Building Tomorrow’s Tech, Today!', 'Будуємо технології завтрашнього дня сьогодні!', 'Budujeme technológie zajtrajška, už dnes!', 'Budowanie technologii jutra, dziś!\r\n', 'Создаем технологии завтрашнего дня, уже сегодня!', 'Wir bauen die Technologie von morgen, schon heute!'),
(12, 'Our cases', 'Наші проєкти', 'Naše práce', 'Nasze prace', 'Наши работы', 'Unsere Arbeiten'),
(13, 'Websites and bots', 'Веб-сайти та Telegram-боти', 'Webstránky a Telegram-boti', 'Strony internetowe i Telegram-boty\r\n', 'Веб-сайты и Telegram-боты', 'Websites und Telegram-Bots'),
(14, '\'Etalon\' website', 'Веб-сайт \'Etalon\'', '\'Etalon\' webstránka', 'Strona \'Etalon\'', 'Веб-сайт \'Etalon\'', '\'Etalon\' Website'),
(15, 'The website was created on a turnkey basis for the customer <br>The site presents the \'Etalon\' plant, products, contacts, information about the plant, etc <br>The site is written in React and PHP using OctoberCMS for easy site administration (change of information on the site). <br>Link to the site: <a href=\'https://etalon-uman.pp.ua/en\' style=\'text-decoration:none;\'>Etalon</a>', 'Сайт був створений під ключ для замовника<br> На сайті представлений завод \'Еталон\', продукція, контакти, інформація про завод і т.д.<br> Сайт написаний на React і PHP з використанням OctoberCMS для зручного адміністрування сайтом <br>Посилання на сайт: <a href=\'https://etalon-uman.pp.ua\' style=\'text-decoration:none;\'>Еталон</a>', 'Webstránka bola vytvorená na kľúč pre zákazníka <br>Stránka predstavuje závod \'Etalon\', produkty, kontakty, informácie o závode atď. <br>Stránka je napísaná v React a PHP s použitím OctoberCMS pre jednoduchú správu stránky (zmena informácií na stránke) <br>Odkaz na stránku: <a href=\'https://etalon-uman.pp.ua/en\' style=\'text-decoration:none;\'>Etalon</a> ', 'Strona została stworzona na zlecenie klienta w trybie \"pod klucz\" <br>Przedstawia zakład \'Etalon\', produkty, kontakty, informacje o zakładzie itp. <br>Strona napisana w React i PHP z użyciem OctoberCMS do łatwej administracji stroną (zmiana informacji na stronie) <br>Link do strony: <a href=\'https://etalon-uman.pp.ua/en\' style=\'text-decoration:none;\'>Etalon</a>\r\n', 'Вебсайт создан под ключ для клиента <br>Сайт представляет завод \'Etalon\', продукцию, контакты, информацию о заводе и т.д. <br>Сайт написан на React и PHP с использованием OctoberCMS для легкого администрирования сайта (изменение информации на сайте) <br>Ссылка на сайт: <a href=\'https://etalon-uman.pp.ua/ru\' style=\'text-decoration:none;\'>Etalon</a>', 'Die Website wurde schlüsselfertig für den Kunden erstellt <br>Die Seite präsentiert das \'Etalon-Werk\', Produkte, Kontakte, Informationen über das Werk usw <br>Die Seite ist in React und PHP geschrieben und verwendet OctoberCMS für eine einfache Site-Administration (Änderung der Informationen auf der Site) <br>Link zur Seite: <a href=\'https://etalon-uman.pp.ua/en\' style=\'text-decoration:none;\'>Etalon</a> '),
(16, 'Dictionary Bot', 'Dictionary Bot', 'Dictionary Bot', 'Dictionary Bot', 'Dictionary Bot', 'Dictionary Bot'),
(17, 'Bot for recording words and translating them into other languages (using DeepL API)<br>The SQLite3 database is used to store the recorded words of the client and the client base<br>At the request of the client, a permanent backup of the database to Google Drive is implemented<br>Deployed on Render hosting<br>Bot\'s username in Telegram: <a href=\'https://t.me/dict1onarybot\' style=\'text-decoration:none;\'>@dict1onarybot</a>', 'Бот для запису слів та перекладу їх на інші мови (за допомогою API DeepL)<br> Для зберігання записаних слів клієнта та клієнтської бази використовується база даних SQLite3 <br>За бажанням клієнта реалізовано постійне резервне копіювання бази даних на Google Drive<br> Розгорнуто на хостингу Render користувача <br>Bot\'s username in Telegram: <a href=\'https://t.me/dict1onarybot\' style=\'text-decoration:none;\'>@dict1onarybot</a>', 'Bot na zaznamenávanie slov a ich preklad do iných jazykov (s použitím DeepL API)<br>Databáza SQLite3 sa používa na ukladanie zaznamenaných slov klienta a klientskej základne <br>Na žiadosť klienta je implementovaná trvalá záloha databázy na Google Drive <br>Nasadené na hosťovaní Render<br>Bot\'s username in Telegram: <a href=\'https://t.me/dict1onarybot\' style=\'text-decoration:none;\'>@dict1onarybot</a>', 'Bot do zapisywania słów i tłumaczenia ich na inne języki (z wykorzystaniem API DeepL) <br>Do przechowywania zapisanych słów i bazy danych klientów używana jest baza SQLite3<br> Na życzenie klienta implementowany jest stały backup bazy danych do Google Drive <br>Bot jest wdrożony na hostingu Render<br>Bot\'s username in Telegram: <a href=\'https://t.me/dict1onarybot\' style=\'text-decoration:none;\'>@dict1onarybot</a>', 'Бот для записи слов и их перевода на другие языки (с использованием DeepL API) <br>Для хранения записанных слов клиента и клиентской базы используется база данных SQLite3<br> По запросу клиента реализовано постоянное резервное копирование базы данных на Google Drive <br>Развернут на Render хостинге<br>Bot\'s username in Telegram: <a href=\'https://t.me/dict1onarybot\' style=\'text-decoration:none;\'>@dict1onarybot</a>', 'Bot zum Aufzeichnen von Wörtern und Übersetzen in andere Sprachen (unter Verwendung der DeepL API) <br>Die SQLite3-Datenbank wird verwendet, um die aufgezeichneten Wörter des Kunden und die Kundendatenbank zu speichern <br>Auf Anfrage des Kunden wird ein permanentes Backup der Datenbank auf Google Drive implementiert<br> Bereitgestellt auf Render-Hosting<br>Bot\'s username in Telegram: <a href=\'https://t.me/dict1onarybot\' style=\'text-decoration:none;\'>@dict1onarybot</a>'),
(18, 'Enroll in Pavel Trusov VIP Bot', 'Enroll in Pavel Trusov VIP Bot', 'Enroll in Pavel Trusov VIP Bot', 'Enroll in Pavel Trusov VIP Bot', 'Enroll in Pavel Trusov VIP Bot', 'Enroll in Pavel Trusov VIP Bot'),
(19, 'A turnkey bot created for an influencer<br>Used to accept subscription payments through the Stripe payment system <br>All data required for the customer is stored in the SQLite3 database <br>The bot is deployed on Render hosting <br>Bot\'s username in Telegram: <a href=\'https://t.me/trusov_vip_bot\' style=\'text-decoration:none;\'>@trusov_vip_bot</a>', 'Бот під ключ, створений на замовлення інфлюенсера <br>Використовується для купівлі підписок різної тривалості через платіжну систему Stripe <br>Всі необхідні для клієнта дані зберігаються в базі даних SQLite3 <br>Бот розгорнуто на хостингу Render <br>Bot\'s username in Telegram: <a href=\'https://t.me/trusov_vip_bot\' style=\'text-decoration:none;\'>@trusov_vip_bot</a>', 'Bot na kľúč, vytvorený na objednávku influencera <br>Používa sa na nákup predplatného rôznych dĺžok prostredníctvom platobného systému Stripe <br>Všetky potrebné údaje sú uložené v databáze SQLite3 <br>Bot je nasadený na hosťovaní Render <br>Telegram username: <a href=\'https://t.me/trusov_vip_bot\' style=\'text-decoration:none;\'>@trusov_vip_bot</a>', 'Bot stworzony na zamówienie influencera <br>Służy do zakupu subskrypcji o różnych długościach poprzez system płatności Stripe <br>Wszystkie dane wymagane przez klienta są przechowywane w bazie SQLite3 <br>Bot jest wdrożony na hostingu Render <br>Bot\'s username in Telegram: <a href=\'https://t.me/trusov_vip_bot\' style=\'text-decoration:none;\'>@trusov_vip_bot</a>', 'Бот под ключ, созданный по заказу влиятельной личности <br>Используется для покупки подписок разной продолжительности через платежную систему Stripe <br>Все необходимые данные для клиента хранятся в базе данных SQLite3 <br>Бот развернут на Render хостинге <br>Bot\'s username in Telegram: <a href=\'https://t.me/trusov_vip_bot\' style=\'text-decoration:none;\'>@trusov_vip_bot</a>', 'Ein schlüsselfertiger Bot, der auf Bestellung eines Influencers erstellt wurde <br>Er wird verwendet, um Abonnements verschiedener Dauer über das Stripe-Zahlungssystem zu erwerben <br>Alle erforderlichen Daten werden in der SQLite3-Datenbank gespeichert <br>Der Bot ist auf Render-Hosting bereitgestellt <br>Bot\'s username in Telegram: <a href=\'https://t.me/trusov_vip_bot\' style=\'text-decoration:none;\'>@trusov_vip_bot</a>'),
(21, 'Our skills', 'Наші навички', 'Naše zručnosti', 'Nasze umiejętności', 'Наши навыки', 'Unsere Fähigkeiten'),
(22, 'Web Development', 'Веб-розробка', 'Webový vývojv', 'Tworzenie stron www', 'Веб-разработка', 'Webentwicklung'),
(23, 'We offer web development services, including custom design, API implementation, database integration, full-stack development, and hosting. Select individual services or order a turnkey website', 'Ми пМи пропонуємо послуги з веб-розробки, включаючи індивідуальний дизайн, реалізацію API, інтеграцію баз даних, full-stack розробку та хостинг. Виберіть окремі послуги або замовте сайт \"під ключ\"', 'Ponúkame služby vývoja webových stránok vrátane vlastného dizajnu, implementácie API, integrácie databáz, vývoja full-stack a hostingu. Vyberte si jednotlivé služby alebo si objednajte webové stránky na kľúč', 'Oferujemy usługi tworzenia stron internetowych, w tym niestandardowe projektowanie, implementację API, integrację baz danych, rozwój Full-Stack i hosting. Wybierz poszczególne usługi lub zamów stronę internetową \"pod klucz\"', 'Мы предлагаем услуги по разработке веб-сайтов, включая индивидуальный дизайн, внедрение API, интеграцию баз данных, full-stack разработку и хостинг. Выберите отдельные услуги или закажите сайт \"под ключ\"', 'Wir bieten Webentwicklung an: Design, API-Integration, Datenbanken, Full-Stack-Entwicklung und Hosting. Wählen Sie Dienstleistungen oder eine schlüsselfertige Website'),
(24, 'Custom design', 'Індивідуальний дизайн', 'Vlastný dizajn', 'Indywidualny design', 'Индивидуальный дизайн', 'Individuelles Design'),
(25, 'API implementation', 'Реалізація API', 'Implementácia API', 'Implementacja API', 'Реализация API', 'API-Implementierung'),
(26, 'Database integration', 'Інтеграція баз даних', 'Integrácia databázy', 'Integracja bazy danych', 'Интеграция базы данных', 'Datenbankintegration'),
(27, 'Payment processing', 'Обробка платежів', 'Spracovanie platieb', 'Przetwarzanie płatności', 'Обработка платежей', 'Zahlungsabwicklung'),
(28, 'Full-stack development', 'Full-stack розробка', 'Full-stack vývoj', 'Full-stack development', 'Full-stack разработка', 'Full-Stack-Entwicklung'),
(29, 'Deployment', 'Розгортання', 'Nasadenie', 'Wdrożenie', 'Развертывание', 'Bereitstellung'),
(30, 'Hosting', 'Хостинг', 'Hosting', 'Hosting', 'Хостинг', 'Hosting'),
(31, 'Telegram Bots', 'Telegram-боти', 'Telegram boti', 'Boty Telegram', 'Telegram боты', 'Telegram-Bots'),
(32, 'Creation of Telegram bots of any complexity for your own needs or business. Everything according to your specifications: design, functionality, API, database, hosting deployment', 'Створення Telegram-ботів будь-якої складності для власних потреб або бізнесу. Все за вашим технічним завданням: дизайн, функціонал, API, база даних, розміщення на хостингу', 'Tvorba Telegram botov akejkoľvek zložitosti pre vaše vlastné potreby alebo podnikanie. Všetko podľa vašich špecifikácií: dizajn, funkčnosť, API, databáza, nasadenie na hosťovaní', 'Tworzenie Botów Telegram o dowolnej złożoności na potrzeby własne lub biznesowe. Wszystko zgodnie z Twoimi specyfikacjami: projekt, funkcjonalność, API, baza danych, wdrożenie na hosting', 'Создание Telegram-ботов любой сложности для ваших нужд или бизнеса. Все по вашим спецификациям: дизайн, функциональность, API, база данных, развертывание на хостинге', 'Erstellung von Telegram-Bots jeder Komplexität für Ihre eigenen Bedürfnisse oder Ihr Unternehmen. Alles gemäß Ihren Vorgaben: Design, Funktionalität, API, Datenbank, Bereitstellung auf Hosting'),
(33, 'Any database', 'Будь-яка база даних', 'Akákoľvek databáza', 'Dowolna baza danych', 'Любая база данных', 'Jede Datenbank'),
(34, 'Payment system in the bot', 'Система оплати в боті', 'Platobný systém v botovi', 'System płatności w bocie', 'Платежная система в боте', 'Zahlungssystem im Bot'),
(35, 'Any payment system', 'Будь-яка платіжна система', 'Akýkoľvek platobný systém', 'Dowolny system płatności', 'Любая платежная система', 'Jedes Zahlungssystem'),
(36, 'Implementation of any APIs', 'Імплементація будь-яких API', 'Implementácia akýchkoľvek API', 'Implementacja dowolnych API', 'Реализация любых API', 'Implementierung von beliebigen APIs'),
(37, 'UI/UX Design', 'UI/UX Дизайн', 'UI/UX Dizajn', 'UI/UX Design', 'UI/UX Дизайн', 'UI/UX Design'),
(38, 'Our designer can develop an individual design according to your wishes for a website or application', 'Наш дизайнер може розробити індивідуальний дизайн відповідно до ваших побажань для веб-сайту або додатку', 'Náš dizajnér môže vyvinúť individuálny dizajn podľa vašich želaní pre webovú stránku alebo aplikáciu', 'Nasz projektant może opracować indywidualny projekt zgodnie z Twoimi życzeniami na stronę internetową lub aplikację', 'Наш дизайнер может разработать индивидуальный дизайн по вашим пожеланиям для сайта или приложения', 'Unser Designer kann ein individuelles Design nach Ihren Wünschen für eine Website oder Anwendung entwickeln'),
(39, 'Just describe your idea and that\'s it!', 'Просто опишіть свою ідею - це все!', 'Stačí opísať svoj nápad a to je všetko!', 'Wystarczy opisać swój pomysł i to wszystko!\r\n', 'Просто опишите свою идею, и все!', 'Beschreiben Sie einfach Ihre Idee und das war\'s!'),
(40, 'SEO', 'SEO', 'SEO', '', 'SEO', 'SEO'),
(41, 'Our SEO services enhance your website\'s visibility on search engines through keyword optimization, content strategy, technical SEO, and link building', 'Наші SEO-послуги підвищують видимість вашого сайту в пошукових системах завдяки оптимізації ключових слів, контент-стратегії, технічного SEO та нарощування бази посилань', 'Naše služby SEO zvyšujú viditeľnosť vašej webovej stránky vo vyhľadávačoch prostredníctvom optimalizácie kľúčových slov, stratégie obsahu, technickej SEO a budovania odkazov', 'Nasze usługi SEO zwiększają widoczność witryny w wyszukiwarkach poprzez optymalizację słów kluczowych, strategię treści, techniczne SEO i budowanie linków', 'Наши SEO-услуги повышают видимость вашего сайта в поисковых системах за счет оптимизации ключевых слов, контент-стратегии, технического SEO и наращивания ссылочной базы', 'Unsere SEO-Dienstleistungen erhöhen die Sichtbarkeit Ihrer Website in Suchmaschinen durch Keyword-Optimierung, Content-Strategie, technische SEO und Link Building'),
(42, 'Contacts', 'Зворотній зв\'язок', 'Kontakty', 'Kontakt', 'Контакты', 'Kontakte'),
(43, 'Communication', 'Зв\'язок з нами', 'Komunikácia', 'Komunikacja', 'Коммуникация', 'Kommunikation'),
(44, 'Fill in the contact information below and describe your project', 'Заповніть контактну інформацію нижче та опишіть Ваш проєкт', 'Vyplňte kontaktné informácie nižšie a opíšte svoj projekt', 'Wypełnij poniższe dane kontaktowe i opisz swój projekt', 'Заполните контактную информацию ниже и опишите свой проект', 'Füllen Sie die Kontaktinformationen aus und beschreiben Sie Ihr Projekt'),
(45, 'Your name', 'Ваше ім\'я', 'Vaše meno', 'Twoje imię', 'Ваше имя', 'Ihr Name'),
(46, 'Email address', 'Електронна адреса', 'E-mailová adresa', 'Adres e-mail\r\n', 'Адрес электронной почты', 'E-Mail-Adresse'),
(47, 'Describe your project', 'Опишіть Ваш проєкт', 'Opíšte svoj projekt', 'Opisz swój projekt', 'Опишите Ваш проект', 'Beschreiben Sie Ihr Projekt'),
(48, 'Enter your question or message', 'Введіть своє повідомлення або запитання', 'Zadajte svoju otázku alebo správu', 'Wpisz swoje pytanie lub wiadomość', 'Введите ваш вопрос или сообщение', 'Geben Sie Ihre Frage oder Nachricht ein'),
(49, 'Submit', 'Надіслати', 'Odoslať', 'Wyślij', 'Отправить', 'Absenden'),
(50, 'Navigation', 'Навігація', 'Navigácia', 'Nawigacja', 'Навигация', 'Navigation'),
(51, 'What do we offer?', 'Що ми пропонуємо?', 'Čo ponúkame?', 'Co oferujemy?', 'Что мы предлагаем?', 'Was bieten wir an?'),
(52, 'Have any questions?', 'Маєте якісь запитання?', 'Máte otázky?', 'Masz jakieś pytania?', 'Остались какие-нибудь вопросы?', 'Haben Sie Fragen?'),
(53, 'We aim to improve your search rankings and drive organic traffic for sustained growth', 'Ми прагнемо покращити ваші пошукові рейтинги та залучити органічний трафік для стійкого зростання', 'Naším cieľom je zlepšiť vaše pozície vo vyhľadávaní a zvýšiť organickú návštevnosť pre trvalý rast', 'Naszym celem jest poprawa pozycji w rankingach wyszukiwania i zwiększenie ruchu organicznego w celu zapewnienia trwałego wzrostu', 'Мы стремимся повысить ваш рейтинг в поисковой выдаче и привлечь органический трафик для устойчивого роста', 'Unser Ziel ist es, Ihr Suchranking zu verbessern und organischen Traffic für nachhaltiges Wachstum zu generieren'),
(54, 'Describe your idea here or leave a message', 'Опишіть свій задум тут або залиште повідомлення', 'Opíšte svoj nápad tu alebo zanechajte správu', 'Opisz swój pomysł tutaj lub zostaw wiadomość', 'Опишите свою идею здесь или оставьте сообщение', 'Beschreiben Sie Ihre Idee hier oder hinterlassen Sie eine Nachricht'),
(55, 'Service', 'Послуга', 'Služba', 'Usługa', 'Услуга', 'Dienst'),
(56, 'Telegram Bot', 'Telegram Bot', 'Telegram Bot', 'Telegram Bot', 'Telegram Bot', 'Telegram Bot'),
(57, 'Web Site', 'Веб-сайт', 'Web-stránka', 'Website', 'Веб-сайт', 'Web-Site'),
(58, 'Custom', 'Власна', 'Vlastné', 'Własna', 'Собственная', 'Eigener'),
(59, 'Pioneering Web Development and AI Implementation to Elevate Your Business...', 'Новаторська веб-розробка та впровадження штучного інтелекту для розвитку вашого бізнесу...', 'Priekopnícky vývoj webových aplikácií a implementácia umelej inteligencie na pozdvihnutie vášho podnikania...', 'Pionierskie tworzenie stron internetowych i wdrażanie sztucznej inteligencji w celu podniesienia...', 'Новаторская веб-разработка и внедрение искусственного интеллекта для повышения эффективности вашего бизнеса...', 'Bahnbrechende Web-Entwicklung und KI-Implementierung, um Ihr Geschäft zu verbessern...'),
(60, 'WebSockets implementation', 'Інтеграція WebSockets', 'Implementácia WebSockets', 'Implementacja WebSockets', 'Реализация WebSockets', 'Web-Sockets-Implementierung'),
(61, 'Project budget', 'Бюджет проекту', 'Rozpočet projektu', 'Budżet projektu', 'Бюджет проекта', 'Budget des Projekts'),
(62, 'Tools', 'Інструменти', 'Nástroje', 'Narzędzia', 'Инструменты', 'Werkzeuge'),
(63, 'Our SEO services boost your website\'s organic traffic, improving product sales and brand awareness.  Partner with us for innovative, high-quality web solutions that drive engagement and growth', 'Наші SEO-послуги збільшують органічний трафік вашого сайту, підвищуючи продажі та впізнаваність бренду.  Співпрацюйте з нами для отримання інноваційних, високоякісних веб-рішень, які сприяють залученню та зростаннюм', 'Naše SEO služby zvyšujú organickú návštevnosť vašej webstránky, zlepšujú predaj produktov a povedomie o značke. Spolupracujte s nami na inovatívnych, kvalitných webových riešeniach, ktoré podporujú angažovanosť a rast', 'Nasze usługi SEO zwiększają ruch organiczny na Twojej stronie internetowej, poprawiając sprzedaż produktów i świadomość marki. Współpracuj z nami, aby uzyskać innowacyjne, wysokiej jakości rozwiązania internetowe, które zwiększą zaangażowanie i wzrost', 'Наши SEO-услуги увеличивают органический трафик вашего сайта, улучшая продажи продуктов и узнаваемость бренда. Партнерство с нами — это инновационные, высококачественные веб-решения, которые повышают вовлеченность и рост', 'Unsere SEO-Dienstleistungen steigern den organischen Traffic Ihrer Website, verbessern den Produktverkauf und das Markenbewusstsein. Arbeiten Sie mit uns für innovative, qualitativ hochwertige Weblösungen, die Engagement und Wachstum fördern'),
(64, '€100', '₴2000', '€100', 'zł400', '€100', '€100'),
(65, '€100 - €300', '₴2000 - ₴8000', '€100 - €300', 'zł400 - zł1200', '€100 - €300', '€100 - €300'),
(66, '€300 - €500', '₴8000 - ₴15000', '€300 - €500', 'zł1200 - zł2200', '€300 - €500', '€300 - €500'),
(67, '€500+', '₴15000+', '€500+', 'zł2200+', '€500+', '€500+'),
(68, 'Create your own Telegram bot!', 'Створи власного Telegram бота!', 'Vytvorte si vlastného bota Telegram!', 'Stwórz własnego bota Telegram!', 'Создай собственного Telegram бота!', 'Erstelle deinen eigenen Telegram-Bot!'),
(69, 'Improve your search rankings!', 'Покращіть свої пошукові рейтинги!', 'Zlepšite si pozície vo vyhľadávaní!', 'Ulepsz swoje rankingi wyszukiwania!', 'Повысьте свой рейтинг в поиске!', 'Verbessern Sie Ihr Suchranking!'),
(70, 'Develop your website!', 'Створіть свій сайт!', 'Vytvorte si vlastnú webovú stránku!', 'Stwórz własną stronę internetową!', 'Создайте свой сайт!', 'Erstellen Sie Ihre eigene Website!'),
(71, 'Our Web Parsing and Web Scraping service efficiently extracts valuable data from websites, including competitors\' data, audience insights, and catalogues', 'Наші послуги Web Parsing та Web Scraping ефективно витягують цінну інформацію з веб-сайтів, включаючи дані про конкурентів, інформацію про аудиторію та каталоги', 'Naša služba Web Parsing a Web Scraping efektívne získava cenné údaje z webových stránok vrátane údajov o konkurencii, prehľadov o publiku a katalógov', 'Nasza usługa Web Parsing i Web Scraping skutecznie wyodrębnia cenne dane ze stron internetowych, w tym dane konkurencji, spostrzeżenia odbiorców i katalogi', 'Наши услуги по Web-парсингу и Web-скрапингу позволяют эффективно извлекать ценные данные с веб-сайтов, включая данные конкурентов, сведения об аудитории и каталоги', 'Unser Web Parsing- und Web Scraping-Service extrahiert auf effiziente Weise wertvolle Daten von Websites, einschließlich Daten von Wettbewerbern, Einblicke in die Zielgruppe und Kataloge'),
(72, 'Extract valuable information for your needs!', 'Витягуємо цінну інформацію для ваших потреб!', 'Vyťažte cenné informácie pre svoje potreby!', 'Wyciągnij cenne informacje dla swoich potrzeb!', 'Извлекайте ценную информацию для своих нужд!', 'Extrahieren Sie wertvolle Informationen für Ihren Bedarf!'),
(73, '€100 - €300 ', 'від ₴2000<br>до ₴8000', '€100 - €300', 'od zł400<br>do zł1200', '€100 - €300', '€100 - €300'),
(74, '€300 - €500 ', 'від ₴8000<br>до ₴15000', '€300 - €500', 'od zł1200<br>do zł2200', '€300 - €500', '€300 - €500'),
(75, 'Your order was successfully sent!', 'Ваше замовлення успішно відправлено!', 'Vaša objednávka bola úspešne odoslaná!', 'Twoje zamówienie zostało pomyślnie wysłane!', 'Ваш заказ успешно отправлен!', 'Ihre Bestellung wurde erfolgreich gesendet!');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `languages`
--
ALTER TABLE `languages`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `languages`
--
ALTER TABLE `languages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=76;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
